# Generated by Django 2.0.6 on 2018-10-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Year_of_birth', models.IntegerField()),
                ('Aa_number_id', models.IntegerField(unique=True)),
                ('sex', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_AID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aadhar', to='mainapp.Aadhar_card')),
            ],
        ),
        migrations.CreateModel(
            name='Voter_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=30)),
                ('v_age', models.IntegerField()),
                ('v_id', models.IntegerField(unique=True)),
                ('v_address', models.CharField(max_length=300)),
                ('v_sex', models.CharField(max_length=5)),
                ('v_Dob', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='v_VID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='mainapp.Voter_id'),
        ),
    ]
