# Generated by Django 2.0.6 on 2018-10-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_loc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='contestent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_img', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='voter',
            name='v_AID',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='v_VID',
        ),
        migrations.AddField(
            model_name='aadhar_card',
            name='v_VID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='mainapp.Voter_id'),
        ),
        migrations.DeleteModel(
            name='voter',
        ),
        migrations.AddField(
            model_name='contestent',
            name='c_AID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_number', to='mainapp.Aadhar_card'),
        ),
        migrations.AddField(
            model_name='contestent',
            name='const_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency_id', to='mainapp.constituency'),
        ),
        migrations.AddField(
            model_name='voter_id',
            name='c_CID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='constituency_ID', to='mainapp.constituency'),
        ),
    ]
