# Generated by Django 2.0.6 on 2018-10-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181004_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_votes', models.IntegerField()),
                ('contestent_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constestent_id', to='mainapp.contestent')),
            ],
        ),
    ]
