# Generated by Django 2.0.6 on 2018-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181004_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter_id',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='votes',
            name='number_votes',
            field=models.IntegerField(default=0),
        ),
    ]
