# Generated by Django 2.0.6 on 2018-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181004_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='contestent_ID',
        ),
        migrations.RemoveField(
            model_name='voter_id',
            name='voted',
        ),
        migrations.AddField(
            model_name='aadhar_card',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestent',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='votes',
        ),
    ]
