# Generated by Django 2.0.6 on 2018-10-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20181004_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_oname', models.CharField(max_length=30, unique=True)),
                ('e_password', models.CharField(max_length=13)),
                ('e_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencyID', to='mainapp.constituency')),
            ],
        ),
    ]
