# Generated by Django 2.0.6 on 2018-10-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_e_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_officer',
            name='e_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencyID', to='mainapp.constituency', unique=True),
        ),
    ]
