# Generated by Django 2.0.6 on 2018-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20181004_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestent',
            name='c_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
